# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 23:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0007_auto_20150916_0305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='emailaddress',
            options={'verbose_name_plural': 'Email addresses'},
        ),
        migrations.AddField(
            model_name='phone',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessiontype',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_type', to='mainsite.Session'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='address2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='edit_time',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='shoot_time',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='sessiontype',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
